### ISSUE TITLE
Unable to provide params without exceptions

### ISSUE THREAD

**Issue by NorthMcCormick** [IndicoDataSolutions/IndicoIo-PHP#91]
I am attempting to grab 1 single language from the language commands, and in doing so I get exceptions thrown that I can't seem to understand. 

`$languageTest = IndicoIo::language($resultQ["arrResponse"][$j], array("top_n" => 1));`

```
IndicoIo\\IndicoIo::language() /Users/north/Documents/development/src/core/models/coreClasses/Checkup/SurveyResponses.php:341
[Thu Oct 20 11:10:56.631812 2016] [:error] [pid 27056] [client ::1:51794] PHP   7. IndicoIo\\IndicoIo::_callService() /Users/north/Documents/development/src/core/phplib/IndicoIo/IndicoIo.php:74
[Thu Oct 20 11:10:56.631837 2016] [:error] [pid 27056] [client ::1:51794] PHP   8. IndicoIo\\IndicoIo::api_url() /Users/north/Documents/development/src/core/phplib/IndicoIo/IndicoIo.php:259
[Thu Oct 20 11:10:57.412511 2016] [:error] [pid 27056] [client ::1:51794] PHP Fatal error:  Uncaught exception 'Exception' with message 'No such command `Array` for api `indicoapi.ML.language.v1`' in /Users/north/Documents/development/src/core/phplib/IndicoIo/IndicoIo.php:301\nStack trace:\n#0 /Users/north/Documents/development/src/core/phplib/IndicoIo/IndicoIo.php(74): IndicoIo\\IndicoIo::_callService('Dignissimos ass...', 'language', Array)\n#1 /Users/north/Documents/development/src/core/models/coreClasses/Checkup/SurveyResponses.php(341): IndicoIo\\IndicoIo::language('Dignissimos ass...')\n#2 /Users/north/documents/development/src/core/models/coreClasses/Checkup/CheckupReportDisplay.php(692): SurveyResponses->__construct('204')\n#3 /Users/north/documents/development/src/core/models/coreClasses/Checkup/CheckupReportDisplay.php(383): CheckupReportDisplay->_getResponses()\n#4 /Users/north/documents/development/src/core/models/coreClasses/Checkup/CheckupReportDisplay.php(366): CheckupReportDisplay->_process()\n#5 /Users/north/documents/development/src/core/htdocs/talentCheckupReport.php(24): CheckupReportDisp in /Users/north/Documents/development/src/core/phplib/IndicoIo/IndicoIo.php on line 301
```

This happens with any added parameters I try and use. 

The docs and the php lib don't seem to be accurate?

OS: OS X El Capitan
PHP: 5.5.33

**Comment by madisonmay** [comment]
Should be merging in a fix here soon. The issue was specific to our language API -- was a problem with positional arguments.

**Comment by madisonmay** [comment]
Thanks for the bug report!

**Comment by madisonmay** [comment]
Try updating your indico version to the most recent master branch and rerunning the script -- you should now be good to go.  Sorry for the trouble!
